{% set version = "1.4" %}
{% set sha256 = "312b5c6abbc87c4d274b61c1cb47059765066c6c7abcd6ba1e60141274e09bf0" %}

package:
  name: libdeflate
  version: {{ version }}

source:
  url: https://github.com/ebiggers/libdeflate/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Build-dylib-on-MacOS.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('libdeflate', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libdeflate.a            # [unix]
    - test -f ${PREFIX}/lib/libdeflate${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/ebiggers/libdeflate
  license: MIT
  license_file: COPYING
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression and decompression.

extra:
  recipe-maintainers:
    - dpryan79
