{% set version = "1.6" %}
{% set sha256 = "60748f3f7b22dae846bc489b22a4f1b75eab052bf403dd8e16c8279f16f5171e" %}

package:
  name: libdeflate
  version: {{ version }}

source:
  url: https://github.com/ebiggers/libdeflate/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libdeflate', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libdeflate.a            # [unix]
    - test -f ${PREFIX}/lib/libdeflate${SHLIB_EXT}  # [unix]
    - libdeflate-gzip -h
    - libdeflate-gunzip -h

about:
  home: https://github.com/ebiggers/libdeflate
  license: MIT
  license_file: COPYING
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression and decompression.

extra:
  recipe-maintainers:
    - dpryan79
    - rhpvorderman
